[package]
name = "lxc"
version = "0.3.0"
authors = ["Sanpi <sanpi@homecomputing.fr>", "Evgenii Lepikhin <e.lepikhin@corp.mail.ru>" ]
repository = "https://github.com/johnlepikhin/lxc-rs.git"
documentation = "https://docs.rs/lxc"
keywords = ["lxc"]
license = "MIT"
categories = ["api-bindings"]
description = "Linux Containers API"
edition = "2018"

[dependencies]
bitflags = "1.0"

[dependencies.lxc-sys]
version = "0.2"
path = "./lxc-sys"

[features]
v1_0 = []
v1_1 = ["v1_0"]
v2_0 = ["v1_1"]
v2_1 = ["v2_0"]
v3_0 = ["v2_1"]
v3_1 = ["v3_0"]
v3_2 = ["v3_1"]

[badges]
travis-ci = { repository = "sanpii/lxc-rs" }
gitlab = { repository = "sanpi/lxc-rs" }
